### ISSUE TITLE
Are you aware of this?

### ISSUE THREAD

**Issue by Lewiscowles1986** [Faryshta/yii2-enum#2]
http://php.net/manual/en/class.splenum.php

**Comment by samdark** [comment]
That's cool but it's not there out of the box: `PECL spl_types >= 0.1.0`.

**Comment by Faryshta** [comment]
also this functionality is more about human-readable text for  usage in views and validations.

And some of the enumerations might use functions that are not valid on compilation time such as `Yii::t()`

**Comment by Lewiscowles1986** [comment]
:wink: noted, although I'm not sure your implementation is as much enumerations as hash keys then?

**Comment by Faryshta** [comment]
I don't understand your question, sorry.
